# Site settings
title: Jack's Package Store | Mountain Home, AR
email: elibrumley@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Jack's Package Store is located at Mountain Home, AR. We offer a vast variety of well-known Liquors, wines, & drink essentials.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jackspackagestore.com/" # the base hostname & protocol for your site
facebook_username: jackspackagestore
github_username:  jekyll

# Build settings
markdown: kramdown
